name: REMX

on:
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: MX Server Restart
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ./restart.sh
          host: ${{ secrets.HOST }}
          username: root
          password: ${{ secrets.PASSWORD }}

      - name: Update log.txt
        run: |
          var=`date +%Y%m%d%H%M`
          echo $var | tee -a log.txt

      - name: Commit
        run: |
          git add log.txt
          var=`date +%Y%m%d%H%M`
          git commit -m $var
          git push origin main
          
      - run: echo "Action Finish"
